In [1]:
import numpy as np
np.random.seed(42)
scores = np.random.randint(50, 101, size=(5, 3))
subject_means = scores.mean(axis=0)
centered_scores = scores - subject_means
print("Original Scores:\n", scores)
print("\nSubject-wise Means:\n", subject_means)
print("\nCentered Scores (after broadcasting):\n", centered_scores)

Original Scores:
 [[88 78 64]
 [92 57 70]
 [88 68 72]
 [60 60 73]
 [85 89 73]]

Subject-wise Means:
 [82.6 70.4 70.4]

Centered Scores (after broadcasting):
 [[  5.4   7.6  -6.4]
 [  9.4 -13.4  -0.4]
 [  5.4  -2.4   1.6]
 [-22.6 -10.4   2.6]
 [  2.4  18.6   2.6]]
