In [1]:
a = [1,2,3,4,5]
b = [6,7,8,9,10]
a + b

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [2]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
    --------------------------------------- 0.3/12.4 MB ? eta -:--:--
    --------------------------------------- 0.3/12.4 MB ? eta -:--:--
    --------------------------------------- 0.3/12.4 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.4 MB 583.3 kB/s eta 0:00:21
   - -------------------------------------- 0.5/12.4 MB 583.3 kB/s eta 0:00:21
   --- ------------------------------------ 1.0/12.4 MB 755.7 kB/s eta 0:00:16
   ---- ----------------------------------- 1.3/12.4 MB 879.3 kB/s eta 0:00:13
   ----- ---------------------------------- 1.6/12.4 MB 944.2 kB/s eta 0:00:12
   ------ --------------------------------- 2.1/12.4 MB 1.1 MB/s eta 0:00:10
   ------- -------------------


[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np

In [5]:
[a[i] + b[i] for i in range(len(a))]

[7, 9, 11, 13, 15]

In [6]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
a + b

array([ 7,  9, 11, 13, 15])

In [7]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr[1:,1:]  # start_row:end_row, start_col:end_col

array([[5, 6],
       [8, 9]])

In [11]:
arr[:,1:2]

array([[2],
       [5],
       [8]])

In [13]:
arr[1:,:2]

array([[4, 5],
       [7, 8]])

In [16]:
arr[1:,1:]

array([[5, 6],
       [8, 9]])

In [17]:
arr[2:,1:]

array([[8, 9]])

In [21]:
arr[:1,1:]

array([[2, 3]])

In [22]:
arr[:2,:1]

array([[1],
       [4]])

In [23]:
arr[1:,[0,2]]

array([[4, 6],
       [7, 9]])

In [26]:
arr[0:2,[0,2]]

array([[1, 3],
       [4, 6]])

In [25]:
arr[0:,[0,2]]

array([[1, 3],
       [4, 6],
       [7, 9]])