In [1]:
a = [1,2,3,4,5]
b = [6,7,8,9,10]
a + b

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [2]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
    --------------------------------------- 0.3/12.4 MB ? eta -:--:--
    --------------------------------------- 0.3/12.4 MB ? eta -:--:--
    --------------------------------------- 0.3/12.4 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.4 MB 583.3 kB/s eta 0:00:21
   - -------------------------------------- 0.5/12.4 MB 583.3 kB/s eta 0:00:21
   --- ------------------------------------ 1.0/12.4 MB 755.7 kB/s eta 0:00:16
   ---- ----------------------------------- 1.3/12.4 MB 879.3 kB/s eta 0:00:13
   ----- ---------------------------------- 1.6/12.4 MB 944.2 kB/s eta 0:00:12
   ------ --------------------------------- 2.1/12.4 MB 1.1 MB/s eta 0:00:10
   ------- -------------------


[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np

In [5]:
[a[i] + b[i] for i in range(len(a))]

[7, 9, 11, 13, 15]

In [6]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
a + b

array([ 7,  9, 11, 13, 15])

In [7]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr[1:,1:]  # start_row:end_row, start_col:end_col

array([[5, 6],
       [8, 9]])

In [11]:
arr[:,1:2]

array([[2],
       [5],
       [8]])

In [13]:
arr[1:,:2]

array([[4, 5],
       [7, 8]])

In [16]:
arr[1:,1:]

array([[5, 6],
       [8, 9]])

In [17]:
arr[2:,1:]

array([[8, 9]])

In [21]:
arr[:1,1:]

array([[2, 3]])

In [22]:
arr[:2,:1]

array([[1],
       [4]])

In [23]:
arr[1:,[0,2]]

array([[4, 6],
       [7, 9]])

In [26]:
arr[0:2,[0,2]]

array([[1, 3],
       [4, 6]])

In [25]:
arr[0:,[0,2]]

array([[1, 3],
       [4, 6],
       [7, 9]])

In [27]:
np.eye(3,3).astype("int32").dtype

dtype('int32')

In [28]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
a

array([1, 2, 3, 4, 5])

In [31]:
a[a>2]

array([3, 4, 5])

In [32]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [33]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
##Vector Operations


In [36]:
a = np.array([1,2,3])
a*2

array([2, 4, 6])

In [37]:
a = np.array([1,2,3])
a+2

array([3, 4, 5])

In [ ]:
# vector Operations

a = np.array([1,2,3])
a**2 # element-wise exponentiation

array([1, 4, 9])

In [41]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [42]:
a**b

array([[    1,    64],
       [ 2187, 65536]])

In [43]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [44]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [45]:
np.linalg.det(a)

np.float64(-2.0000000000000004)

In [46]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [49]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  4,  1])

In [48]:
a = np.array([1,2,3,4,5,6,7,8,9,10,4,1])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  4,  1])

In [50]:
np.reshape(np.reshape(a,(3,4)),(6,2))

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [ 4,  1]])

In [51]:
np.resize(a,(3,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10,  4,  1]])

In [52]:
np.split(a,2)

[array([1, 2, 3, 4, 5, 6]), array([ 7,  8,  9, 10,  4,  1])]

In [61]:
#Copy and Views

from array import array
arr = np.array([1,2,3,4,5])
b = arr.view()


In [63]:
b[0] = 10
arr,b


(array([10,  2,  3,  4,  5]), array([10,  2,  3,  4,  5]))

In [64]:

c = arr.copy()
arr,c



(array([10,  2,  3,  4,  5]), array([10,  2,  3,  4,  5]))

In [69]:


c[0] = 11

In [71]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [77]:
np.sum(a,axis=0)

np.int64(60)

In [78]:
np.sum(a,axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [79]:
data = [10, 20, 30, 40, 50]

mean = sum(data) / len(data)

print("Mean:", mean)


Mean: 30.0


In [80]:
def mean(array):
    n = len(array)
    return sum(array) / n

In [84]:
mean(np.array([10,20,30,40,50,60]))

np.float64(35.0)

In [85]:
def variance(array):
    n = len(array)
    m = mean(array)
    return sum((x - m) ** 2 for x in array) / n

In [86]:
variance(np.array([1,2,3,4,5,6]))

np.float64(2.9166666666666665)

In [87]:
mean(np.array([10,20,30,40,50]))

np.float64(30.0)